import Image from 'next/image';
import Head from 'next/head';
import hari from '../public/hari.jpg';
import cartoonHari from '../public/cartoonHari.jpeg'

export default function Home() {
  return (
    <div>
      <Head>
      <title>Hari Chidambaram</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="flex flex-col items-center justify-center md:flex-row">
        <div className="flex flex-col items-center w-3/4 md:w-1/2 mr-8 pt-4">
          <h1 className="text-3xl font-bold bg-gradient-to-r from-purple-500 via-pink-500 to-red-500 bg-clip-text text-transparent py-2 text-center">
            Hi! I&apos;m Hariharan (Hari) Chidambaram
          </h1>
          <p className="text-lg font-bold text-center pb-4 w-4/5">
            I am a senior at the University of Michigan studying Computer Science and am particularly interested in Security
            and Cloud Engineering. I am currently a Software Engineering Intern at{' '}
            <a href="https://valon.com/" className="text-blue-500 hover:underline">
              Valon
            </a>{' '} where I am working on their Escrow team.
              Outside of the tech world, I have a passion for tennis and various endurance sports, particularly Nordic Skiing and Triathlons!
          </p>
        </div>
        <div className="relative">
          <Image src={hari} alt="Hari's Photo" layout="fixed" objectFit="cover" className='w-80 rounded-full transition-opacity duration-300 ease-in opacity-100 hover:opacity-0' />
          <Image src={cartoonHari} alt="Hari's Photo" layout="fixed" objectFit="cover" className='w-80 rounded-full absolute top-0 left-0 transition-opacity duration-300 ease-in opacity-0 hover:opacity-100' />
        </div>
      </div>
    </div>

  );
}

